### ISSUE TITLE
Minor: Permissions

### ISSUE THREAD

**Issue by garethahealy** [makentenza/ocp-pinpoint-apm#6]
Re-use the fix-permissions script

https://github.com/makentenza/ocp-pinpoint-apm/blob/master/Dockerfile#L58-L60

**Comment by makentenza** [comment]
Yes, and we need also to review how to run this as a random user as now require root user to start the process.

    # oadm policy add-scc-to-user anyuid system:serviceaccount:pinpoint-apm:pinpoint
